config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  get '/auth/spotify/callback', to: 'users#spotify'
  delete '/user', to: 'users#destroy'
  resources :genres, only: [:index]
  get '/songs', to: 'songs#show', as: 'song'
  get '/songs/new', to: 'songs#create', as: 'create_song'
  get '/song', to: 'songs#destroy', as: 'delete_song'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  def index
    categories = RSpotify::Category.list
    @genres = {}
    categories.each do |category|
      @genres[category.name] = category.icons.first["url"]
    end
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  include SongsHelper

  def create
    @tracks = params[:tracks].as_json
    @genre = params[:genre]
    track_id = @tracks.first["id"]
    track = RSpotify::Track.find("#{track_id}")
    @tracks.delete_at(0)
    user = RSpotify::User.new(session[:user])
    playlist = user.playlists.find {|playlist| playlist.name == "Samplify-#{@genre}"}
    playlist.add_tracks!([track])
    user.save_tracks!([track])
    @track = @tracks.first
    @name = @track["name"]
    @preview = @track["preview"]
    @artist = @track["artist"]
    @id = @track["id"]
    @img = @track["img"]
    render :show
  end

  def show
    @genre = params[:genre]
    spotify_user = RSpotify::User.new(session[:user])
    existing_playlist = spotify_user.playlists.find {|playlist| playlist.name == "Samplify-#{@genre}"}
    @playlist = spotify_user.create_playlist!("Samplify-#{@genre}") unless existing_playlist
    category = RSpotify::Category.find("#{set_genre(@genre)}")
    playlists = category.playlists
    @tracks = []
    i = 0
    playlists.shuffle.each do |playlist|
      playlist.tracks.shuffle.each do |track|
        next unless track.name && track.preview_url && track.artists && track.id && track.album.images
        break if i >= 20
        @tracks[i] = { name: track.name,
                       preview: track.preview_url,
                       artist: track.artists.first.name,
                       id: track.id,
                       img: track.album.images.first["url"]
                    }
        i += 1
      end
    end
    @track = @tracks.shuffle.first
    @name = @track[:name]
    @preview = @track[:preview]
    @artist = @track[:artist]
    @id = @track[:id]
    @img = @track[:img]
  end

  def destroy
    @tracks = params[:tracks].as_json
    @genre = params[:genre]
    @tracks.delete_at(0)
    @track = @tracks.first
    @name = @track["name"]
    @preview = @track["preview"]
    @artist = @track["artist"]
    @id = @track["id"]
    @img = @track["img"]
    render :show
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def spotify
    spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
    session[:user] = spotify_user
    # playlist = spotify_user.create_playlist!('this-created-with-oauth')
    # tracks = RSpotify::Track.search('Video Games')
    # playlist.add_tracks!(tracks)
    redirect_to '/genres'
  end

  def destroy
    session.clear
    redirect_to :root
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    RSpotify::Category.list
    binding.pry
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/genre_helper.rb
module GenreHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
  def set_genre(genre)
    case genre
    when "Folk & Americana"
      return "folk_americana"
    when "Indie"
      return "indie_alt"
    when "Trending"
      return "popculture"
    when "EDM/Dance"
      return "edm_dance"
    else
      return genre.downcase.tr(" ", "")
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/genres/index.html.erb
<div class="overlay">
<div class="overlay-message">
    <h1>LOADING...</h1>
</div>
</div>

<div class="container">
	  <h1 class="genre-header">CATEGORIES</h1>
	  <div class="row">
	    <div class="col s12 card-holder">
			<% @genres.each do |name, img| %>
		    	<div class="card genre-card col s6">
					<%= link_to song_path(genre: name) do %>
			  		<%= image_tag(img, :class => "card-image ")%>
			  		<h3 class="card-content"><%= name %></h3>
					<% end %>
				</div>
		  	<% end %>
		</div>

	</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Samplify</title>

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    
    <div class="header">
      <div class="left"> 
        <i class="medium material-icons">queue_music</i>  
        <h3 class="brand-logo">Samplify</h3>
      </div>

      <div class="right">
        <% if session[:user] %>
        <%= link_to 'Logout', '/user', method: :delete, class: "waves-effect waves-light btn-large" %>
        <% end %>
      </div>
    </div>
   
    <%= yield %>
  </body>
</html>

app/views/songs/show.html.erb
<div class="container">
  <h1 class="song-genre-header"><%=@genre%></h1>
  <div class="col s12 song-holder">
     <%= link_to "< CATEGORIES", genres_path, class: "waves-effect waves-light btn-large", id: "back" %>
      <div class="song-card">
        <%= image_tag(@img, :class => "card-image song-image col s6 ")%>
          <audio class = "hidden" src = "<%=@preview %>" controls autoplay></audio>
          <div class="song-content">
          <h2 class="song-name"><%=@name%></h2>
          <h4 class="song-artist"><%=@artist%></h4><br><br>
          <%= link_to "SKIP", delete_song_path(tracks: @tracks, genre: @genre), class: "waves-effect waves-light btn-large red" %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
          <%= link_to "ADD SONG", create_song_path(tracks: @tracks, genre: @genre), class: "waves-effect waves-light btn-large" %>
        </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= user %><br><%= playlists %><br><%= recommendations %>

app/views/welcome/index.html.erb
  <div class="container">
    <div class="home-image-inner-container">
    	
		    <h4 class="home-text">Find Your Next Musical Adventure</h4>
		    <div class="signin-button"><%= link_to 'Sign in with Spotify', '/auth/spotify', class: "waves-effect waves-light btn-large" %>
		    </div>
	    
    </div>
  </div>